---
version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    target-branch: '1.x'
    commit-message:
      prefix: 'chore: ðŸ¤–'
    labels:
      - 'dependabot'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
